### ISSUE TITLE
Load from Gitlab

### ISSUE THREAD

**Issue by cophilot** [cophilot/templify#11]
The `load` command takes a GitHub URL to fetch some predefined templates from a repository. This should also be possible with a Gitlab repository URL. The functionality should not be changes and for the user it should not make a difference if it is a GitHub or a Gitlab URL.

Use [this Gitlab repo](https://gitlab.com/cophilot/templify-vault) for testing purposes.

**Comment by cophilot** [comment]
This is a bit harder issue and involves some more complex operations, like fetching data over an API, but if you want, I think it would be a good issue for your @RounakJoshi09 :)

**Comment by RounakJoshi09** [comment]
Sure thing @cophilot , I would definitely take this up and solve it asap.
Thanks for assigning,

**Comment by cophilot** [comment]
> Sure thing @cophilot , I would definitely take this up and solve it asap.
> Thanks for assigning,

Thanks and don't hurry @RounakJoshi09 take your time. It is not urgent...

**Comment by RounakJoshi09** [comment]
Hi @cophilot , hope you're having a great week. 
I have almost completed with the functionality , just have to write test cases for the implemented feature.
For that purpose can you please add Test template in this gitlab repository https://gitlab.com/cophilot/templify-vault,
as it is present in GitHub Repository, so that I can reuse the existing tests of load.

![image](https://github.com/user-attachments/assets/aeeef628-d2f0-4dfa-b635-41bce04a1479)

Thanks
